### ISSUE TITLE
APIドキュメントが見れない

### ISSUE THREAD

**Issue by kamekyame** [kakomimasu/viewer#76]
https://kakomimasu.com/docs/apiv1 は見れるが、そのほかのAPIドキュメントが以下の表示が出て見れない。

```
{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: href.split(...).at is not a function\nPlease report this to https://github.com/markedjs/marked.","trace":["Runtime.UnhandledPromiseRejection: TypeError: href.split(...).at is not a function","Please report this to https://github.com/markedjs/marked.","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:314:20)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
```

markedのエラーっぽいが、localhostでは動く。mdのfetchがうまくできていない可能性…

**Comment by kamekyame** [comment]
Fix #77
